import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Teleprompter from "./components/teleprompter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className="antialiased max-w-5xl mb-40 flex flex-col md:flex-row mx-4 mt-8 lg:mx-auto" >
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          <Teleprompter/>
          {/* <form action="">
            <input type="text" name="" id="" placeholder="Enter text" />
          </form> */}
        </main>
      </body>
    </html>
  );
}
